apiVersion: v1
kind: PersistentVolume
metadata:
  name: homebridge-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: {{ storage.nfs.base_path }}/homebridge-data
    server: {{ storage.nfs.server }}
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: homebridge-data
  storageClassName: nfs
