---
creation_rules:
  - path_regex: kluctl/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1f2jtd5x763dcwjfndnjmcu6mxphmhvl5s5tchz8j6mcavl873a9qmfpflj
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1f2jtd5x763dcwjfndnjmcu6mxphmhvl5s5tchz8j6mcavl873a9qmfpflj
