---
kubernetes:
  children:
    master:
      vars:
        ansible_user: pi
        ansible_ssh_port: 22
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      hosts:
        k8s-0:
          ansible_host: 192.168.178.21
        k8s-1:
          ansible_host: 192.168.178.22
    worker:
      vars:
        ansible_user: pi
        ansible_ssh_port: 22
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      hosts:
        k8s-2:
          ansible_host: 192.168.178.23
