apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: {{ dns.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - dns01:
          cnameStrategy: Follow
          route53:
            region: eu-central-1
            accessKeyID: {{ dns.route53.access_key_id }}
            secretAccessKeySecretRef:
              name: letsencrypt-route53
              key: secret-access-key
        selector:
          dnsZones:
            - {{ dns.base }}
