apiVersion: apps/v1
kind: Deployment
metadata:
  name: ix500-scanner
  labels:
    app: ix500-scanner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ix500-scanner
  template:
    metadata:
      labels:
        app: ix500-scanner
    spec:
      containers:
        - name: ix500-scanner
          image: docker-registry.homelab.codablock.de/ix500-scanner
          imagePullPolicy: Always
          env:
            - name: TZ
              value: {{ apps.timezone }}
          volumeMounts:
            - mountPath: /dev/bus/usb
              name: usb
            - mountPath: /pdfs
              name: pdfs
          securityContext:
            privileged: true
      volumes:
        - name: usb
          hostPath:
            path: /dev/bus/usb
        - name: pdfs
          persistentVolumeClaim:
            claimName: pdfs
      nodeSelector:
        kubernetes.io/hostname: k8s-4
