apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: {{ storage.nfs.base_path }}/mosquitto-data
    server: {{ storage.nfs.server }}
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mosquitto-data
  storageClassName: nfs
