mqtt_shelly_config:
    mqtt:
        host: ENC[AES256_GCM,data:UjPHddfxZLs03prtaXc=,iv:rMwUs/Zb32HGQP3khuq1t1ky8KLJQNKtexBWXp+airo=,tag:ahEoIW7uPntsbNQzfLTWgQ==,type:str]
        port: ENC[AES256_GCM,data:6dmfSQ==,iv:y62dzvR2i0Aqjo9OFOuSgeic5rFB2uENDf/abSbsW8I=,tag:Emvf11odIMD3P2tTbpBiKQ==,type:int]
        username: ENC[AES256_GCM,data:t/y4Rdx4,iv:u2oui6h31Lm4ZstPq/ARkl7XzyfTg7PQr0JI+ObkGfo=,tag:kaYpvzb1YkTEcwjBAT/dPw==,type:str]
        password: ENC[AES256_GCM,data:lDwQrb3x0Tf/Tieat+ks+tB8sOc=,iv:0aCoGXmNwNHKHQKgFIClrXIF8hYi2C3uRP6i4+r60Iw=,tag:m9Dsx7ndmYp1rmwcTuNVHQ==,type:str]
    shellies:
        login:
            username: ENC[AES256_GCM,data:mHkfdaZl,iv:OwhWQqrylNIKPZDicKMwQapiXkkFTh8/eRoPo2w1iUs=,tag:XLn4F8E4vsIlNL9gixEjYw==,type:str]
            password: ENC[AES256_GCM,data:wjfp45qjsrUKD8NU6ZuMYw==,iv:9ARtkLlOec00MYzFyViyPutaikmzFkWUkDWg76tRRRA=,tag:SGCcEB5r2TowDB/P5X/6tQ==,type:str]
        network:
            cidr: ENC[AES256_GCM,data:js7/Z5Iy2U/PtH+WKO2bZg==,iv:TrAV34WUPcnO6cZmtIT5NMYTeRKbAu/1kxwZ8KJCOM8=,tag:C9pOnoVsfSdDA5HwT428EA==,type:str]
            mask: ENC[AES256_GCM,data:gVLCE5uUszOAVG2eHA==,iv:ScFAmvCdUo1Jal8Q7WNWY2Ajhhq1b9+w17DfPe1QAZ0=,tag:sXj33ga3411rBbfhpvg6Hw==,type:str]
            gw: ENC[AES256_GCM,data:ofuBNOYccwk9z5ep+g==,iv:uIP236rKvq0LTa4UBAPhYjpDZZHMmPIxBc6l4vR/OlA=,tag:Kys9A+naucarWAs1hK1tXg==,type:str]
            dns: ENC[AES256_GCM,data:QwkON13IycLH3rXI5w==,iv:bLVn4+Sh6w9A+mzhxHSVSLaCwYahpHfMa2JQlSyiHUQ=,tag:9fCe6txPH626i/olFu4QqQ==,type:str]
            ips: {}
    #ENC[AES256_GCM,data:t0DlyHlKP44hmbnWpsf2sL8Gl8pYxHvyw72rtEneWKOWFumN,iv:vKy1mjEI3B+K+/PE4uC1Veodn9Mr73DCvvCxWszPZxY=,tag:JDaW0XjZLLmGZfeGHMeeMQ==,type:comment]
    homebridge:
        url: ENC[AES256_GCM,data:V+Xwogr0sVTUKSPRAMOItlAwjEzEtFDlubDntHXoT15O5kJFiJtO,iv:wyr2c3WWjsbEDs0xNI06t/u+czpXWsmEIOzW8MEsUsk=,tag:HOqcw8MVa2i4JvlvYLqgvg==,type:str]
        username: ENC[AES256_GCM,data:ap4uCPc=,iv:fLd2JA/x7nTtmytf98ed+cEjalYKPH9r+RkL/aYjG6U=,tag:xzjs1/FpPHI/V7drqaq6Zg==,type:str]
        password: ENC[AES256_GCM,data:42a3wX/ZdWcmTHBzUerdWQ==,iv:19ZLC0sONHMxQX4KPOOda6KTRQJOw/IrWe8lRi+QByc=,tag:sbDjOUrZuuT65hwnn/bLhQ==,type:str]
    accessories:
        lights:
            - name: ENC[AES256_GCM,data:bE3eBqXp,iv:4gvF2gcaDLPjHMJowMYzEUa+Io7IM9alUq1B/cVrLJQ=,tag:Z27sIIormClpIw06mzaNKQ==,type:str]
              switchTopic: ENC[AES256_GCM,data:cmx4F8j5kWcVLldY+PQuPn977Ux5B9iNElTkqOMMLu21IeGtKQ==,iv:8vyjHT3W2UO6R9Diba84i7SGNt3+wzhuADeStlFKiVo=,tag:om3RP9v6MiDKHRFLanxQSA==,type:str]
            - name: ENC[AES256_GCM,data:FlU9TDjN26wlVw==,iv:OLxBxlASzOFje723MEb/lmEuSfyBXFX8bT43d2mINBw=,tag:RWZ2JIH85cffZR08XdPnkA==,type:str]
              switchTopic: ENC[AES256_GCM,data:MzqR5FitzwgEqFKPGiLbFxsGpvF8izIUsg9wycm44mv7X3D90Q==,iv:Kd9HQ6jAp0epBgatz4Iw6Lmgr6hZFR8aZqk0g8fqqhk=,tag:sDAWmV9TEWKdxtyYA6RmhA==,type:str]
            - name: ENC[AES256_GCM,data:Y/1M1VR4gFULwFhrNwjl,iv:pG9Zci1Uvi74ydl1mCRS3FD0UqHL8guYKPNx6ZMQulQ=,tag:wEwRHxAaWyQ1A7TwRETDxA==,type:str]
              dimmable: ENC[AES256_GCM,data:e/TPiw==,iv:lTTxHNYJW1fwuzBM3GRCQfCrY7pL5oA5hhBFIUcWWZA=,tag:nq2k9CfMySSwYIDVZZfHDg==,type:bool]
              switchTopic: ENC[AES256_GCM,data:oH4GRWlVPGrZ9I40IX1GR7TbzMKC+zPnUp5LyQSSJhjws7mUacl+DUeXOw==,iv:lEMQRkeI8KwJiZ1JcsuyAEwZqPcg5BQbuYeI63mK0z4=,tag:XiZyzPs3sdW/3+xkhca+dw==,type:str]
            - name: ENC[AES256_GCM,data:PVlT4C804QiWrtLUsbj4AGfjDg==,iv:KYNjy0hGAIN4JeXxLGOfLgsY0q8aJ+7ep4ML42vNUnM=,tag:+S230YEUl+nZ/eAFEUgUvA==,type:str]
              switchTopic: ENC[AES256_GCM,data:9hTP0f1PoA+afgGHtPzvykYPTKsu/7SPg7TBbIMtkkt25DhK1w==,iv:fcQccZ5jEevIbuhR4JiD8Dkp22GgXxfhM7d7Mri0rIA=,tag:XTGtqDZNdGpXVipSkPCKGg==,type:str]
            - name: ENC[AES256_GCM,data:anpYDiEwlFsTFCRBjqgDSKGs,iv:uGsXIV4I7j17LTOM+iYP8gVwVupr6w0vmNDH4qiAH4E=,tag:4Ospr2MVJiMAbcTDE+pNnA==,type:str]
              switchTopic: ENC[AES256_GCM,data:nGzSTz4qXHC75vOzo52aKncQ5rDMf9MSpdTPei8lAmsV3Awi,iv:Nb54E82o/mjpLsq6T8bJNRHeMCZEv31D3QXfB/q3koI=,tag:xVEXXy8QUQCtb/RszntySA==,type:str]
            - name: ENC[AES256_GCM,data:3NcEcfhIX6Y4nPs5VKhutQ==,iv:rz/khCowB+FZQDD/JbjVyiItrmv8siXnGG8vEE4K7qI=,tag:WPo22jRxTLg1dReeRRtcDA==,type:str]
              switchTopic: ENC[AES256_GCM,data:BEP3cAUMfsP0w9eb84/bYujiWMHRLwcypnJ2xrN48pUMmjUPhg==,iv:msaZlC+5YxjFavlQgVyuSfw3OZsQ89CCfsmP6OM4FEw=,tag:NrcLIyb0XhTmd0ppNpo6Vw==,type:str]
            - name: ENC[AES256_GCM,data:WU7Sl9fYP2e8hruA,iv:vun4J6B46E80Rex74flTbrORlTVz7xiPjFvC70I5kuQ=,tag:5mHgF2d2wsFKKKgxZBiTPw==,type:str]
              switchTopic: ENC[AES256_GCM,data:KdnblJ78J0n/6GQD2aOp9YacyRHwLhf1RPBunY98Qw2jnkAMrw==,iv:TH7K5jflo9IrrRqwmqq2x1utUxzUWvGPDCn0VhkKV+U=,tag:UZQrM7HJr3qhb9kFVvgiYg==,type:str]
            - name: ENC[AES256_GCM,data:9v/f51mBH3hVi8Y=,iv:Fr+EC+kpVay51cQR5XmlB0kdTPQzJ9l8o84fIZr7yhQ=,tag:PmhZ3iB3ur9EC4pEs4mUEA==,type:str]
              switchTopic: ENC[AES256_GCM,data:OlPYo3iHFX3bex2kJuaA8CeRhBsO7fZkXoHMqvWLXWOo6pxbSIYp5S7dIpY=,iv:XdlvfyzpX2nHx2BjmAfPkULgFwIMxDLaCTeKjXfrqC0=,tag:gr0JKCJJhe732u72pT02fQ==,type:str]
            - name: ENC[AES256_GCM,data:TdthS+MDkov1r/WG,iv:+t/VduzYKRCSoRVTUolhjV8romBnYkFkhAKyX+MSE4Q=,tag:6R+hrg80f+MmYmUQ3Trepg==,type:str]
              switchTopic: ENC[AES256_GCM,data:NBH4msBKjqyypVHZhYgEE8XwmDgoVkfHKw5EsOcjsPpuSR9CC9EVpLTMnX0=,iv:4EaUG+kTRk2A0gbTRzsGR/83QwBHOTr2kv5z3x944xY=,tag:v//+MgJFX+9CDNandK091w==,type:str]
            - name: ENC[AES256_GCM,data:k8RLnSKsDBo1yDgK,iv:rZs3dQXgh4LVg76vIYC9IMBv5DVhKds3/UNrTes9JZ0=,tag:uqOqrC+2WDHn46g1gr+oQQ==,type:str]
              switchTopic: ENC[AES256_GCM,data:37Tjg/9Yj7J8RSGSsoWtG49gJyyMV+rzkgCMoq/EOB0Dw8r0wnHfnQNyhws=,iv:jq64IB8Z7ItCfDDYMxwsGEBLJaovm+qY3gw944W5Vdg=,tag:LsgO49N2SN1tl/5UFVCn8g==,type:str]
            - name: ENC[AES256_GCM,data:DvN0MM7w/L1ciHw=,iv:1ydWnz+Pk/Bf0AhNKP3VdQLVUXLM/PdyzoNZHxNCaKQ=,tag:2ckUNBUB9MDjJSJ1zrNe/g==,type:str]
              switchTopic: ENC[AES256_GCM,data:mscQrmLA15AzsFV3t138BWp5lkoq3QqoZXxFAerXezxOiGL/+g==,iv:Nz/DgSmWznjWeHJSL985WwPYcY+pQmJhLTVCMJn2vRg=,tag:KbwG5qz4V54Twb6AZ4gpIA==,type:str]
            - name: ENC[AES256_GCM,data:LPlSTD5cDnsU,iv:z1f0x6xkc59KQNkhMg3H3ik1LOhbOMSwMYZ80Q/lJIM=,tag:OQ0IxFJRywzoNYLBN2bvJA==,type:str]
              switchTopic: ENC[AES256_GCM,data:QFL1W1BWR8nxcq9+585peoXHZzibzacmclCCmds+d6HR1tw7Hw==,iv:NDjNtasDwc7nwJNasre/nWF+WXkwPNSRsJH0rwrN8J0=,tag:zsXwJWbHTLD7u+4hxw05lA==,type:str]
            - name: ENC[AES256_GCM,data:oKzTS6AYDJZyig==,iv:Isrq/Ap0ze4bvFK7K60BEBySmZVQyzfVyIKL2pFWFms=,tag:YnWh1++Dqc3LMXLoPpHAAg==,type:str]
              switchTopic: ENC[AES256_GCM,data:5zF5aSOlZyg3CG8JN2EKDr1kUiGGnjgJVnJyt/pdc3FoLzuPTjxZF7Z+Q7w=,iv:53duEquEQl7sgBdGJxbTFA6gjIEFcNfWtZ6OfDVdZmE=,tag:MzE9KFcLPPbMtH1F6vpceA==,type:str]
            - name: ENC[AES256_GCM,data:nUMLjYzrGR9g5A==,iv:zLoS8COGurBEl7sv1zzrUNMwFbgThr5TNzyQekAwqhY=,tag:a1EENWxco8m8fwP2egMrtw==,type:str]
              switchTopic: ENC[AES256_GCM,data:hbTa7NhWISUfStbxKz96Z/U0LahJa5KR09Zrn99WVju4jMpWCySFIHT8hQo=,iv:0I4/PB7ehd6xddvrFKiWAaMGuV8YkZwmvPmQZxNDOIQ=,tag:p+hwuE3IjA2dgWavy4VyCw==,type:str]
            - name: ENC[AES256_GCM,data:BKQHSobRXJgl,iv:SvVa4n89F4i1xGj2bcXn78yCsEUsaeFv8lk5Adi/N+4=,tag:ZdDQ/Tbcbgvf+gO0G9nLvQ==,type:str]
              switchTopic: ENC[AES256_GCM,data:WfB4HZuWNvjDyCHsQQxqNDwOaFHOiD4bReTOojjwFwtW4lC1zQ==,iv:ZZUXxGkd9as4o1M26CAeVqojB+JNR0DexZL2jNu862s=,tag:F/vnHK5P3QcuNljV+RuYmQ==,type:str]
        switches:
            - name: ENC[AES256_GCM,data:EHWi/0c1wX2xyqO18A==,iv:or7r3XxXFPgQhqXK/lGxUTAQhzYwocvXi3uUEAsTHwY=,tag:ql665JGOmlAnrhYTswWjcA==,type:str]
              switchTopic: ENC[AES256_GCM,data:4WD/kfnfm3udy6R1CxARb7e0RntQLmwESJnhLhBYhvS2p3Fd5Q==,iv:VBKz8skziU4EwnYOVFqY3QEdTxUPajsWoKkNz5M0gaY=,tag:6ZsbwalRh2xcI4KRr1LT5A==,type:str]
        fans:
            - name: ENC[AES256_GCM,data:EVgXCuKul44xlCFayMMpew==,iv:ivLqQrAoa+HgkmNx0jA3MbCAoeeOCDX5tKDsv+RoTSU=,tag:RMR+XxfEC5s3jtjUNmueKA==,type:str]
              switchTopic: ENC[AES256_GCM,data:jWZBqHaY99bpuhlQdL8ERjng8Ack3yD0MIj3ENCekSaDv+xX,iv:ScakX7TsGMYg2MKquXR5Q9vMctg7YUdL3iqSrQc4Iaw=,tag:2eFSQH9+sRRTLBFFAQGAsQ==,type:str]
        temperatureAndHumiditySensors:
            - name: ENC[AES256_GCM,data:mHj695wyhCdyXw==,iv:D7pPhDIuVSInp5Lzxm3ey2d/ofed436JLtKwR0Zao5Q=,tag:kXeSQ4Qp1LUsrcwYwssTtQ==,type:str]
              sensorTopic: ENC[AES256_GCM,data:Vntb9vx6Va3As7QVVezm+kHtHirpgHcAfbQHEdYDfA==,iv:LFb0z+nLLLlgwpfVlC/zyilUYciI0e6YJXylYUaO8q0=,tag:iBP2/r8ZBGw+Bp0UXQHy5w==,type:str]
            - name: ENC[AES256_GCM,data:Tl7xiXtwr0yctvAj,iv:mS8G83zql2wJ0sSW3prynzyeTytzjYHc1FPjsq6DO5A=,tag:zQKApgVgTu52aBO6G+rlMA==,type:str]
              sensorTopic: ENC[AES256_GCM,data:HAhL36hUBufS2usdahsC3rjLXoTEbZyOw37q+/iqLQ==,iv:RbpKnOHHlsbFcKcDKeEYVNMx7I39wR3rMfqoQEBbh9M=,tag:PiXpsR3p0rql3PzsHBRd+A==,type:str]
            - name: ENC[AES256_GCM,data:2OV3lmE2wB85/gsf,iv:I4VmSAaX82ZXgo/3Q4c2OTwIqWF1KVoz02yq5W6KNRQ=,tag:Ecj/gw7B91SXlJk0gXk2ow==,type:str]
              sensorTopic: ENC[AES256_GCM,data:/U7wubaFtTqD3yShr39eyBOstesV1o7rrG0N5tl+VA==,iv:sbdiRGV9ECUYYVfy/XbAPLK9uohQ8mCilZ2gYrdHNs8=,tag:NxbbASohUdQS7j83r8NE6g==,type:str]
        #ENC[AES256_GCM,data:ldFKJ/WGTcS5khsbPYdCR0A=,iv:1RXStxMyZM019MQz0pIH4KThqeVbkuSJtZE0/bJdIfE=,tag:TUAlL2QBEs9o4AuoA25Xyg==,type:comment]
        #ENC[AES256_GCM,data:asZyGBdRBgyOQrII7LA1nz+3MX5D8InhZE1cTGwI0+UCbUuN/A==,iv:5CHJrmKBa5MCdnTlBYYG6jjMzUrkbHqvd2BAvntXjZs=,tag:KbQG9b/CCmCckF9emD16kQ==,type:comment]
        #ENC[AES256_GCM,data:zXDAhFiIDQj8pE0XJittLaWINUnLooO8WbhMFvww,iv:stu6LQ3IIwto6GAVwvsBtkLk1fL6APc0qLas6juJeQg=,tag:EPgTNCbk9kVo5JUXA772xw==,type:comment]
        contactSensors:
            - name: ENC[AES256_GCM,data:8yIs128PXXnWINd8ww==,iv:Z7dlH6uS8Btw5Qxib4v+8iz2jnkg/yxbQ77xhBgDsno=,tag:C4rXRY4Erd9Mv46ZhvRB4A==,type:str]
              sensorTopic: ENC[AES256_GCM,data:9Gp6NAfK8gE/iG4IZlIMzw8X+O1fjtJu4zHxINpvDu88SlysW/M=,iv:1x+PX1ViTK3h8K2M3W7IBTsm0icatzuR2l3Z2kvQTGA=,tag:Te25QNdeQMPY711qOy7Mhg==,type:str]
            - name: ENC[AES256_GCM,data:qlr07rnX7zsuF1yj,iv:gRRAHx9dmQ+KGTj3G1JSBSB+4MJztZqqW4aAPUWBqvI=,tag:/SW+vS6Af/omvhAJihJo2A==,type:str]
              sensorTopic: ENC[AES256_GCM,data:mtVKISWMDP7lHU/fY+kjgRcRa6icGF/UbKgeW6xrd0gPoKFxBzo=,iv:sSkq6312wZcFKOIUJ1uGKzmAvtgad98t1rhgS1L6RQM=,tag:99P7Ca4dQWFOJsptYtD0Kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f2jtd5x763dcwjfndnjmcu6mxphmhvl5s5tchz8j6mcavl873a9qmfpflj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITms2dkpEZmpEYk1PRFJ1
            cE5sZjV3Y0lraXZIQ0xiejhyOHJZdUpnVWtnCnkybitiRDdUZStxQ3o2L2VoeHJX
            RWJPblU3RFg0bVgzbXhrZ0hZcnFqTmsKLS0tIGU4MGxpQzlneWRBbmFscm4zSXJt
            V1FXZlNZTjNsZzJ4dkdTQkltN3pTZmsKWnRFPPpLBAQU8M4DJ2Zf1LJAsbweOprD
            zS6s7F+EhWkafiqDsROMkNNGKkxTzWvMPVBro/g10pw1YwIITRiVTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T23:28:50Z"
    mac: ENC[AES256_GCM,data:Tp/mZv19YVgR5R4JWfItM3EPu13FJWRQtVi9rxb8mRtelN/J0OGUQypApTQP9It2g78n6TfhaG/Lp4/b2uJdxVxuQwkeXfa0iimHYjbRDQSlu8g2h+Ng4Kv6g/3JSy/xWK9s2eLLhua1NjAy873wYySasP6XAgeRVpSqyjZJ6Bs=,iv:ofC2NaBKGaFrzy+78iR04bLFOw12dwpqE3t595P7CMk=,tag:gzHnCH+Kj5JgmD4mRx6HyA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
