apiVersion: v1
kind: Secret
metadata:
  name: external-dns
  namespace: kube-system
stringData:
  rfc2136_tsig_keyname: {{ dns.rfc2136.tsig.keyname }}
  rfc2136_tsig_secret: {{ dns.rfc2136.tsig.secret }}
  rfc2136_tsig_secret_alg: {{ dns.rfc2136.tsig.secret_alg }}
